unique_ids:
  assets:
    standard-page.html: HBLBGHZSB5NHIOIG26WXPJHIJZD54DPC
    theme.css: IWUPMAPJVDTFX7VPWZVPSC52YLQKRDXN
  forms:
    Form1: 26FLU5KGSLEPQDPAR7ZKTDNSZ6UJL2HA
  modules: {}
  scripts: {}
  server_modules: {}
